### PR TITLE
Patches for all my submitted bugs

### PR DESCRIPTION
**Pull request by LRGH**
I did not include the patch for https://github.com/bdcht/amoco/issues/62 because I have yet to test how various CPU (Intel or AMD) behave when executing `66 6A 08`

### CODE REVIEW

**Comment by LRGH** [comment]
Added the pach for https://github.com/bdcht/amoco/issues/62

**Comment by bdcht** [comment]
parts of the request will be merged manually but some testing is required for the performance improvement changes...

**Comment by bdcht** [comment]
I've merged most commits, except for 
- x64 "keep_order" thing which had conflicts that needed more testing and 
- the removed imports in top **init** script.

**Comment by LRGH** [comment]
Hello !
I am surprised that "keep_order" generates conflicts. When this flag is not set, everything should be working exactly as before. The same sequence of operations is made.

**Pull request closed without merging**
